### ISSUE TITLE
Try to run  on GCP

### ISSUE THREAD

**Issue by pvysotskiy** [MSTrll/cool-memes#9]
Просмотреть Cloud'ы:
(Нам нужна бесплатная лицензия. Если совсем нет - то Azure)
Развернуть коннектор в Cloud. (Создать свой кластер, на котором будет приложение, которая будет писать сообщения в файл.
Например "Инкрементальный номер и timestamp" Каждую минуту.
Java, Scala, Python, C/C++ (Java приоритет!)
 Гугловый(Артём);

**Comment by R0o3pER** [comment]
ok

**Comment by mstrell1337** [comment]
@pvysotskiy , look here!

**Comment by mstrell1337** [comment]
$$$$$$
